config:
  # Configuration values to set up basic communication
  # Set your COM port e.g. COM3 for Windows, /dev/ttyACM0 for Linux...
  # Use AUTO for COM port auto-discovery (may not work on every setup)
  # COM_PORT: "/dev/ttyACM0"
  # COM_PORT: "COM3"
  COM_PORT: AUTO

  # Theme to use (located in res/themes)
  # Use the name of the folder as value
  THEME: Pikachu_theme_320x480

  # Hardware sensors reading
  # Choose the appropriate method for reading your hardware sensors:
  # - PYTHON         use Python libraries (psutils, GPUtil...) to read hardware sensors (supports all OS but not all HW)
  # - LHM            use LibreHardwareMonitor library to read hardware sensors (Windows only - NEEDS ADMIN RIGHTS)
  # - STUB / STATIC  use random/static data instead of real hardware sensors
  # - AUTO           use the best method based on your OS: Windows OS will use LHM, other OS will use Python libraries
  HW_SENSORS: PYTHON

  # Network interfaces
  # Linux/MacOS interfaces are named "eth0", "wlan0", "wlp1s0", "enp2s0"...
  # For Windows use the interfaces pretty name: "Ethernet 2", "Wi-Fi", ...
  # Leave the fields empty if the card does not exist on your setup
  ETH: ''     # Ethernet Card
  WLO: ''     # Wi-Fi Card

  # CPU fan
  # For Linux/MacOS platforms, the CPU fan is amongst all fan sensors gathered from the motherboard chipset
  # If value is AUTO the system monitor will try to auto-select the CPU fan
  # If auto-detection fails, it might be necessary to manually indicate which fan is the CPU fan
  # Value must be 'controller/fan' e.g. 'nct6798/fan2'. Use configuration wizard for help in selection
  CPU_FAN: AUTO

display:
  # Display revision:
  # - A_320x480  for WeAct Studio Display FS V1
  # - SIMU_320x480  for 320x480 simulated LCD (image written in screencap.png)
  # - SIMU_480x800  for 480x800 simulated LCD (image written in screencap.png)
  REVISION: A_320x480

  # Display Brightness
  # Set this as the desired %, 0 being completely dark and 100 being max brightness
  # Warning: revision A display can get hot at high brightness!
  BRIGHTNESS: 100

  FREE_OFF: false

  # Display reverse: true/false
  # Set to true to reverse display orientation (landscape <-> reverse landscape, portrait <-> reverse portrait)
  # Note: Display basic orientation (portrait or landscape) is defined by the theme you have selected
  DISPLAY_REVERSE: false
